//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterswitchNameEnquiry.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccessTokenLog
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AccessTokenLog()
        {
            this.DebitTransactionLogs = new HashSet<DebitTransactionLog>();
        }
    
        public long Id { get; set; }
        public string AccessToken { get; set; }
        public string TokenType { get; set; }
        public decimal ExpiresIn { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime ExpiryDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DebitTransactionLog> DebitTransactionLogs { get; set; }
    }
}
