//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterswitchNameEnquiry.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class DebitTransactionLog
    {
        public long Id { get; set; }
        public long TokenId { get; set; }
        public string DestinationBankCode { get; set; }
        public string DestinationAccount { get; set; }
        public string SourceAccount { get; set; }
        public decimal Amount { get; set; }
        public string InterswitchTransactionId { get; set; }
        public string SourceAccountName { get; set; }
        public string DestinationAccountName { get; set; }
        public System.DateTime DateCreated { get; set; }
        public long ChannelId { get; set; }
        public string BankRequestReference { get; set; }
    
        public virtual AccessTokenLog AccessTokenLog { get; set; }
    }
}
